import fluxcySkidModel from '../assets/fluxcy_skid_proxy.glb?url';
import type { DashboardWidgetConfig } from '../types/dashboard';

export const dashboardWidgets: DashboardWidgetConfig[] = [
  {
    id: 'clock-main',
    type: 'clock',
    title: 'Fecha y hora',
    subtitle: 'Actualizacion local',
    timezone: 'America/Mexico_City',
    timeFormat: 'HH:mm:ss',
    dateFormat: 'YYYY-MM-DD',
    colSpan: 3,
    minHeight: 120,
  },
  {
    id: 'metric-pcv',
    type: 'metric',
    title: 'PCV',
    subtitle: 'POS',
    dataKey: 'pcvPos',
    unit: '%',
    decimals: 0,
    colSpan: 3,
    minHeight: 120,
  },
  {
    id: 'metric-densidad-linea',
    type: 'metric',
    title: 'Densidad Linea',
    dataKey: 'densidadLinea',
    unit: 'g/cm',
    decimals: 3,
    colSpan: 3,
    minHeight: 120,
  },
  {
    id: 'metric-gravedad-mezcla',
    type: 'metric',
    title: 'Gravedad Mezcla',
    dataKey: 'gravedadMezcla',
    unit: 'API',
    decimals: 1,
    colSpan: 3,
    minHeight: 120,
  },
  {
    id: 'gauge-tp-liquido',
    type: 'gauge',
    title: 'TP Liquido',
    dataKey: 'tpLiquido',
    min: 0,
    max: 300,
    unit: 'psi',
    decimals: 0,
    thresholds: [
      { value: 180, color: '#3fb950' },
      { value: 240, color: '#f59e0b' },
      { value: 300, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'gauge-dg-flow',
    type: 'gauge',
    title: 'DG Flow',
    subtitle: 'Drive Gain Gas',
    dataKey: 'dgFlow',
    min: 0,
    max: 100,
    unit: '%',
    decimals: 1,
    thresholds: [
      { value: 50, color: '#3fb950' },
      { value: 75, color: '#f59e0b' },
      { value: 100, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'gauge-temp-gas',
    type: 'gauge',
    title: 'Temps',
    subtitle: 'Temperatura Gas',
    dataKey: 'temperaturaGas',
    min: 0,
    max: 140,
    unit: 'F',
    decimals: 1,
    thresholds: [
      { value: 85, color: '#3fb950' },
      { value: 110, color: '#f59e0b' },
      { value: 140, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'gauge-tp-gas',
    type: 'gauge',
    title: 'TP Gas',
    dataKey: 'tpGas',
    min: 0,
    max: 300,
    unit: 'psi',
    decimals: 0,
    thresholds: [
      { value: 180, color: '#3fb950' },
      { value: 240, color: '#f59e0b' },
      { value: 300, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'gauge-drive-liquido',
    type: 'gauge',
    title: 'Drive Gain Liquido',
    dataKey: 'driveGainLiquido',
    min: 0,
    max: 100,
    unit: '%',
    decimals: 1,
    thresholds: [
      { value: 50, color: '#3fb950' },
      { value: 75, color: '#f59e0b' },
      { value: 100, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'gauge-temp-liquido',
    type: 'gauge',
    title: 'Temperatura Liquido',
    dataKey: 'temperaturaLiquido',
    min: 0,
    max: 140,
    unit: 'F',
    decimals: 1,
    thresholds: [
      { value: 85, color: '#3fb950' },
      { value: 110, color: '#f59e0b' },
      { value: 140, color: '#ef4444' },
    ],
    colSpan: 2,
    minHeight: 190,
  },
  {
    id: 'table-pressures',
    type: 'table',
    title: 'Pressures',
    tableKey: 'pressures',
    columns: [
      { key: 'fechaHora', label: 'Fecha y Hora' },
      { key: 'psiCabezal', label: 'PSI Cabezal', align: 'right' },
      { key: 'psiCasing', label: 'PSI Casing', align: 'right' },
      { key: 'psiLinea', label: 'PSI Linea', align: 'right' },
      { key: 'psiMacolla', label: 'PSI Macolla', align: 'right' },
    ],
    colSpan: 12,
    minHeight: 230,
  },
  {
    id: 'model-skid',
    type: 'model',
    title: 'Skid 3D',
    subtitle: 'Vista tecnica',
    src: fluxcySkidModel,
    alt: 'Modelo 3D del skid Fluxcy',
    cameraControls: true,
    autoRotate: true,
    colSpan: 6,
    minHeight: 320,
  },
  {
    id: 'metric-total-liquido',
    type: 'metric',
    title: 'Total Liquido',
    dataKey: 'totalLiquido',
    unit: 'Bls',
    decimals: 1,
    colSpan: 2,
    minHeight: 120,
  },
  {
    id: 'metric-delta-p',
    type: 'metric',
    title: 'Delta P',
    dataKey: 'deltaP',
    decimals: 0,
    colSpan: 2,
    minHeight: 120,
  },
  {
    id: 'metric-total-gas',
    type: 'metric',
    title: 'Total Gas',
    dataKey: 'totalGas',
    unit: 'MSCF',
    decimals: 1,
    colSpan: 2,
    minHeight: 120,
  },
  {
    id: 'chart-flow-rate',
    type: 'chart',
    title: 'Flow Rate',
    seriesKey: 'flowRate',
    xKey: 'time',
    lines: [
      { dataKey: 'gas', name: 'Gas (MSCFD)', color: '#ff8d27' },
      { dataKey: 'liquido', name: 'Liquido (Bls/d)', color: '#8a63ff' },
    ],
    colSpan: 4,
    minHeight: 300,
  },
  {
    id: 'chart-vp',
    type: 'chart',
    title: 'VP',
    seriesKey: 'vp',
    xKey: 'time',
    lines: [
      { dataKey: 'presionGas', name: 'Presion Gas (PSI)', color: '#96c2ff' },
      { dataKey: 'presionLiq', name: 'Presion Liq (PSI)', color: '#ffc53d' },
      { dataKey: 'tempGas', name: 'Temperatura Gas (C)', color: '#8fd3ff' },
      { dataKey: 'tempLiq', name: 'Temperatura Liq (C)', color: '#d9f6ff' },
    ],
    colSpan: 4,
    minHeight: 300,
  },
  {
    id: 'chart-rho',
    type: 'chart',
    title: 'Rho',
    seriesKey: 'rho',
    xKey: 'time',
    lines: [
      { dataKey: 'densidadGas', name: 'Densidad Gas', color: '#a4ff9a' },
      { dataKey: 'densidadLiq', name: 'Densidad Liq', color: '#f6f3e8' },
    ],
    colSpan: 4,
    minHeight: 300,
  },
  {
    id: 'chart-pro-calc',
    type: 'chart',
    title: 'Pro Calc 1m',
    seriesKey: 'proCalc',
    xKey: 'time',
    lines: [
      { dataKey: 'gas', name: 'Gas (MSCF)', color: '#ff8d27' },
      { dataKey: 'liquido', name: 'Liq (Bls)', color: '#2f81f7' },
    ],
    colSpan: 12,
    minHeight: 360,
  },
];
