export const env = {
  appName: 'Fluxcy Dashboard',
  appBasePath: '/',
  apiBaseUrl: 'https://api-sermaca.lat/api_aguilera',
  authLoginPath: '/auth/login',
  dashboardSnapshotPath: '/dashboard/snapshot',
  realtimeBootstrapPath: '/api/realtime/bootstrap',
  realtimeQmrPath: '/api/qmr',
  realtimeVpPath: '/api/vp',
  realtimeRhoPath: '/api/rho',
  realtimeProduccionPath: '/api/produccion',
  realtimePressuresPath: '/api/pressures',
  realtimeTotalPath: '/api/total',
  realtimeRholiqPath: '/api/rholiq',
  realtimeDensidadApiPath: '/api/densidadapi',
  realtimeTempPath: '/api/temp',
  realtimeDrivgainPath: '/api/drivgain',
  realtimePossValvePath: '/api/possvalve',
  socketUrl: 'https://api-sermaca.lat',
  socketNamespace: '/',
  socketPath: '/api_aguilera/socket.io',
  socketUpdateEvent: 'realtime:mediciones',
  socketConnectEvent: 'realtime:subscribe',
  socketSubscribePozo: '',
  socketWithCredentials: false,
  maxSeriesPoints: 120,
  enableDemoMode: false,
  enableLocalAuthFallback: true,
  localAuthUsersPath: '/users.json',
} as const;
